### ISSUE TITLE
CalcView hook does not include nearZ or farZ (and breaks addons that use it)

### ISSUE THREAD

**Issue by ottworks** [BillyTheBull/localizedphysics#9]
ll/cl_main.lua:151
     4. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151
      1. unknown - lua/includes/modules/hook.lua:84

[ERROR] MutatorsForTTT:182: attempt to perform arithmetic on local 'nearz' (a string value)
1. v - MutatorsForTTT:182
   1. Call - lua/includes/modules/hook.lua:84
   2. v - addons/localizedphysics-master/lua/gravityhull/cl_main.lua:151

**Comment by ghost** [comment]
Fixed.
